### ISSUE TITLE
type FileUpload not exported?

### ISSUE THREAD

**Issue by zwily** [mjackson/form-data-parser#2]
I'm getting `FileUpload` is not exported:

```
import { type FileUpload, parseFormData } from "@mjackson/form-data-parser";
```

and it doesn't appear to be exported in `@mjackson/form-data-parser/dist/form-data-parser.d.ts`:

```
export { type FileUploadHandler, parseFormData } from "./lib/form-data.js";
```

Am I missing something?

**Comment by mjackson** [comment]
Ooof, you're right. It wasn't exported from the top-level API. Fixed in https://github.com/mjackson/remix-the-web/commit/88fe17131708db8e9a92c9053e83191035692fce and released in v0.2.0. Thanks for the catch, and sorry for the inconvenience!
