### ISSUE TITLE
Should the upload handler allow returning null?

### ISSUE THREAD

**Issue by jacobparis** [mjackson/form-data-parser#3]
The example upload handler is a bit out of date vs the library 

- should be `fileStorage.set` instead of `fileStorage.put`
- `fileStorage.get` returns `File | null` but the handler function only accepts `File | void`

I can satisfy the current types by writing the example handler as follows 

```ts
const formData = await parseFormData(request, async fileUpload => {
	if (fileUpload.fieldName === 'user-avatar') {
		let storageKey = `user-${user.id}-avatar`

		// FileUpload objects are not meant to stick around for very long (they are
		// streaming data from the request.body!) so we should store them as soon as
		// possible.
		await fileStorage.set(storageKey, fileUpload)

		// Return a File for the FormData object. This is a LazyFile that knows how
		// to access the file's content if needed (using e.g. file.stream()) but
		// waits until it is requested to actually read anything.
		const file = await fileStorage.get(storageKey)
		if (file) {
			return file
		}
	}

	// Ignore any files we don't recognize the name of...
})
```

but I suspect being able to `return fileStorage.get(storageKey)` is expected behaviour without the if wrapper

**Comment by mjackson** [comment]
This is great feedback, thank you. Yes, the upload handler should accept `null`-ish values as a return value. I'll make that update.

**Comment by mjackson** [comment]
This was fixed in https://github.com/mjackson/remix-the-web/commit/00823d8dcc591d53bf423dfba62c0482996b2eb2
