### ISSUE TITLE
console.log(file) calls .size() which throws error

### ISSUE THREAD

**Issue by jacobparis** [mjackson/form-data-parser#4]
If I try to `console.log(file)` inside an upload handler, I get the error from the size method `Cannot get the size of a file upload without buffering the entire file`

Maybe the FileUpload class should implement its own toString() method that doesn't call .size() implicitly, to avoid throwing errors in this case

**Comment by mjackson** [comment]
Yep, I agree. `FileUpload` needs its own `toString()` method.
